use_frameworks!

platform :ios, '11.0'

target 'LCPlayer_Example' do
  pod 'LCPlayer', :path => '../'
  pod 'SDWebImage', '5.16.0'
  target 'LCPlayer_Tests' do
    inherit! :search_paths

    
  end
end
